/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import dominio.Jugador;
import dominio.Partida;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import socketCliente.SocketCliente;

/**
 *
 * @author Itzel
 */
public class FrmConfigurarPartida extends FrmClienteAux {

    private static FrmSeleccion frmSeleccion;
    public static int numCasillas;
    private final int MIN_CASILLAS = 8;
    private final int MAX_CASILLAS = 14;
    public static int numFichas;
    private final int MIN_FICHAS = 2;
    private final int MAX_FICHAS = 6;
    public static int numFondoApuesta;
    private final int MIN_FONDO = 10;
    private final int MAX_FONDO = 10000;

    public FrmConfigurarPartida(SocketCliente cliente, Jugador jugador, Partida partida) {
        super(cliente, jugador, partida);
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumCasillas = new javax.swing.JLabel();
        lblNumFichas = new javax.swing.JLabel();
        lblApuesta = new javax.swing.JLabel();
        btnMenosCasillas = new javax.swing.JLabel();
        btnMasCasillas = new javax.swing.JLabel();
        lblCampoCasillas = new javax.swing.JLabel();
        btnMenosFichas = new javax.swing.JLabel();
        lblCampoFichas = new javax.swing.JLabel();
        btnMasFichas = new javax.swing.JLabel();
        btnMenosApuesta = new javax.swing.JLabel();
        lblCampoApuesta = new javax.swing.JLabel();
        btnMasApuesta = new javax.swing.JLabel();
        btnCrear = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumCasillas.setFont(new java.awt.Font("Eras Bold ITC", 0, 34)); // NOI18N
        lblNumCasillas.setForeground(new java.awt.Color(139, 89, 10));
        lblNumCasillas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasillas.setText("0");
        getContentPane().add(lblNumCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 40));

        lblNumFichas.setFont(new java.awt.Font("Eras Bold ITC", 0, 34)); // NOI18N
        lblNumFichas.setForeground(new java.awt.Color(139, 89, 10));
        lblNumFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumFichas.setText("0");
        getContentPane().add(lblNumFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 100, 40));

        lblApuesta.setFont(new java.awt.Font("Eras Bold ITC", 0, 34)); // NOI18N
        lblApuesta.setForeground(new java.awt.Color(139, 89, 10));
        lblApuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApuesta.setText("0");
        getContentPane().add(lblApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 100, -1));

        btnMenosCasillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn menos.png"))); // NOI18N
        btnMenosCasillas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenosCasillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosCasillasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosCasillasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosCasillasMouseExited(evt);
            }
        });
        getContentPane().add(btnMenosCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 70, -1));

        btnMasCasillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn mas.png"))); // NOI18N
        btnMasCasillas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMasCasillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasCasillasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasCasillasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasCasillasMouseExited(evt);
            }
        });
        getContentPane().add(btnMasCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 70, -1));

        lblCampoCasillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo texto.png"))); // NOI18N
        getContentPane().add(lblCampoCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 80));

        btnMenosFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn menos.png"))); // NOI18N
        btnMenosFichas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenosFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosFichasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosFichasMouseExited(evt);
            }
        });
        getContentPane().add(btnMenosFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 70, -1));

        lblCampoFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo texto.png"))); // NOI18N
        getContentPane().add(lblCampoFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 80));

        btnMasFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn mas.png"))); // NOI18N
        btnMasFichas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMasFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasFichasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasFichasMouseExited(evt);
            }
        });
        getContentPane().add(btnMasFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 70, -1));

        btnMenosApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn menos.png"))); // NOI18N
        btnMenosApuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenosApuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosApuestaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosApuestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosApuestaMouseExited(evt);
            }
        });
        getContentPane().add(btnMenosApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 70, -1));

        lblCampoApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo texto.png"))); // NOI18N
        getContentPane().add(lblCampoApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, 80));

        btnMasApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn mas.png"))); // NOI18N
        btnMasApuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMasApuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasApuestaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasApuestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasApuestaMouseExited(evt);
            }
        });
        getContentPane().add(btnMasApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 70, -1));

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn crear.png"))); // NOI18N
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frm config.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setIcon(new ImageIcon("images\\btn cancelar 2.png"));
    }//GEN-LAST:event_btnCancelarMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setIcon(new ImageIcon("images\\btn cancelar.png"));
    }//GEN-LAST:event_btnCancelarMouseExited

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setIcon(new ImageIcon("images\\btn crear 2.png"));
    }//GEN-LAST:event_btnCrearMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setIcon(new ImageIcon("images\\btn crear.png"));
    }//GEN-LAST:event_btnCrearMouseExited

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnMenosCasillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosCasillasMouseEntered
        btnMenosCasillas.setIcon(new ImageIcon("images\\btn menos 2.png"));
    }//GEN-LAST:event_btnMenosCasillasMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnMenosFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosFichasMouseEntered
        btnMenosFichas.setIcon(new ImageIcon("images\\btn menos 2.png"));
    }//GEN-LAST:event_btnMenosFichasMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnMenosApuestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosApuestaMouseEntered
        btnMenosApuesta.setIcon(new ImageIcon("images\\btn menos 2.png"));
    }//GEN-LAST:event_btnMenosApuestaMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnMasCasillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasCasillasMouseEntered
        btnMasCasillas.setIcon(new ImageIcon("images\\btn mas 2.png"));
    }//GEN-LAST:event_btnMasCasillasMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnMasFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasFichasMouseEntered
        btnMasFichas.setIcon(new ImageIcon("images\\btn mas 2.png"));
    }//GEN-LAST:event_btnMasFichasMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando pase el cursor sobre él.
     *
     * @param evt
     */
    private void btnMasApuestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasApuestaMouseEntered
        btnMasApuesta.setIcon(new ImageIcon("images\\btn mas 2.png"));
    }//GEN-LAST:event_btnMasApuestaMouseEntered

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnMenosCasillasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosCasillasMouseExited
        btnMenosCasillas.setIcon(new ImageIcon("images\\btn menos.png"));
    }//GEN-LAST:event_btnMenosCasillasMouseExited

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnMenosFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosFichasMouseExited
        btnMenosFichas.setIcon(new ImageIcon("images\\btn menos.png"));
    }//GEN-LAST:event_btnMenosFichasMouseExited

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnMenosApuestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosApuestaMouseExited
        btnMenosApuesta.setIcon(new ImageIcon("images\\btn menos.png"));
    }//GEN-LAST:event_btnMenosApuestaMouseExited

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnMasCasillasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasCasillasMouseExited
        btnMasCasillas.setIcon(new ImageIcon("images\\btn mas.png"));
    }//GEN-LAST:event_btnMasCasillasMouseExited

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnMasFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasFichasMouseExited
        btnMasFichas.setIcon(new ImageIcon("images\\btn mas.png"));
    }//GEN-LAST:event_btnMasFichasMouseExited

    /**
     * Evento que cambia la imagen del boton cuando el cursor no esta sobre él.
     *
     * @param evt
     */
    private void btnMasApuestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasApuestaMouseExited
        btnMasApuesta.setIcon(new ImageIcon("images\\btn mas.png"));
    }//GEN-LAST:event_btnMasApuestaMouseExited

    /**
     * Cambia de ventana al frame de inicio.
     *
     * @param evt
     */
    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.setVisible(false);
        this.getInstanciaFrmInicio().setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * Cambia de ventana al frame de selección.
     *
     * @param evt
     */
    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        partida.setFondoApuesta(numFondoApuesta);
        partida.setNumCasillasAspa(numCasillas);
        partida.setNumFichasJugador(numFichas);

        try {
            cliente.setObserver(getFrmSeleccion());
            partida.setJugadorTurno(jugador);
            cliente.enviar(partida);
            getFrmSeleccion().setVisible(true);
            this.setVisible(false);
            this.finalize();
        } catch (IOException ex) {
            Logger.getLogger(FrmConfigurarPartida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Throwable ex) {
            Logger.getLogger(FrmConfigurarPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    /**
     * Evento que incrementa una casilla en la configuración.
     *
     * @param evt
     */
    private void btnMasCasillasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasCasillasMouseClicked
        if (numCasillas != MAX_CASILLAS) {
            numCasillas += 1;
            lblNumCasillas.setText(numCasillas + "");
        }
    }//GEN-LAST:event_btnMasCasillasMouseClicked

    /**
     * Evento que incrementa una ficha en la configuración.
     *
     * @param evt
     */
    private void btnMasFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasFichasMouseClicked
        if (numFichas != MAX_FICHAS) {
            numFichas++;
            lblNumFichas.setText(numFichas + "");
        }
    }//GEN-LAST:event_btnMasFichasMouseClicked

    /**
     * Evento que incrementa el valor de apuesta en la configuración.
     *
     * @param evt
     */
    private void btnMasApuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasApuestaMouseClicked
        if (numFondoApuesta != MAX_FONDO) {
            numFondoApuesta += 10;
            lblApuesta.setText(numFondoApuesta + "");
        }
    }//GEN-LAST:event_btnMasApuestaMouseClicked

    /**
     * Evento que decrementa el valor de las casillas en la configuración.
     *
     * @param evt
     */
    private void btnMenosCasillasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosCasillasMouseClicked
        if (numCasillas != MIN_CASILLAS) {
            numCasillas -= 1;
            lblNumCasillas.setText(numCasillas + "");
        }
    }//GEN-LAST:event_btnMenosCasillasMouseClicked

    /**
     * Evento que decrementa el valor de las fichas en la configuración.
     *
     * @param evt
     */
    private void btnMenosFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosFichasMouseClicked
        if (numFichas != MIN_FICHAS) {
            numFichas--;
            lblNumFichas.setText(numFichas + "");
        }
    }//GEN-LAST:event_btnMenosFichasMouseClicked

    /**
     * Evento que decrementa el valor de apuesta en la configuración.
     *
     * @param evt
     */
    private void btnMenosApuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosApuestaMouseClicked
        if (numFondoApuesta != MIN_FONDO) {
            numFondoApuesta -= 10;
            lblApuesta.setText(numFondoApuesta + "");
        }
    }//GEN-LAST:event_btnMenosApuestaMouseClicked

    /**
     * Inicializa los valores de casillas, fichas y fondo con el valor minimo.
     */
    private void inicializarValores() {
        numCasillas = MIN_CASILLAS;
        numFichas = MIN_FICHAS;
        numFondoApuesta = MIN_FONDO;

        lblNumCasillas.setText(numCasillas + "");
        lblNumFichas.setText(numFichas + "");
        lblApuesta.setText(numFondoApuesta + "");
    }

    /**
     * Centra la pantalla y ajusta las dimensiones dependiendo de la pantalla en
     * el que se ejecute.
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCrear;
    private javax.swing.JLabel btnMasApuesta;
    private javax.swing.JLabel btnMasCasillas;
    private javax.swing.JLabel btnMasFichas;
    private javax.swing.JLabel btnMenosApuesta;
    private javax.swing.JLabel btnMenosCasillas;
    private javax.swing.JLabel btnMenosFichas;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblApuesta;
    private javax.swing.JLabel lblCampoApuesta;
    private javax.swing.JLabel lblCampoCasillas;
    private javax.swing.JLabel lblCampoFichas;
    private javax.swing.JLabel lblNumCasillas;
    private javax.swing.JLabel lblNumFichas;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        adaptarPantalla();
        //this.setBackground(new Color(0, 0, 0, 0));
        inicializarValores();
    }

    public static FrmSeleccion getFrmSeleccion() {
        if (frmSeleccion == null) {
            frmSeleccion = new FrmSeleccion(cliente, jugador, partida);
        }
        return frmSeleccion;
    }

    @Override
    public void update(Partida partidaLlegada) {
        super.update(partidaLlegada);
    }
}
