/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import dominio.Casilla;
import dominio.EstadoPartida;
import dominio.Ficha;
import dominio.Jugador;
import dominio.Partida;
import dominio.Tablero;
import static frames.FrmClienteAux.partida;
import grafico.CnvTablero;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import socketCliente.SocketCliente;

/**
 *
 * @author Invitado
 */
public class FrmTablero extends FrmClienteAux {

    private static FrmSalir frmSalir;
    // private JPanel pnlTablero;
    private CnvTablero cnvTablero;

    /**
     * Creates new form FrmTablero
     */
    public FrmTablero(SocketCliente clienteN, Jugador jugadorN, Partida partidaN) {
        super(clienteN, jugadorN, partidaN);
        initComponents();
        inicializar();
    }

    /**
     * Método que extiende la ventana del frame según la pantalla y dibuja el
     * tablero con cierto número de casillas (Variable)
     */
    private void inicializar() {
        adaptarPantalla();
        extenderPantalla();

        Tablero tablero = partida.getTablero();

        if (partida.getTablero() == null) {
            try {
                tablero = new Tablero();
                cnvTablero = new CnvTablero(tablero.getCasillas(), partida.getNumCasillasAspa(), this.getSize().width);
                tablero.setCasillas(cnvTablero.generarCasillas());
                partida.setTablero(tablero);
                cliente.enviar(partida);
            } catch (IOException ex) {
                Logger.getLogger(FrmTablero.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            cnvTablero = new CnvTablero(tablero.getCasillas(), partida.getNumCasillasAspa(), this.getSize().width);
        }
        if (!jugador.equals(partida.getJugadores().get(0))) {
            btnComenzarPartida.setVisible(false);
        }

        cnvTablero.setSize(this.getWidth(), partida.getNumCasillasAspa() * 50 + (50 * 5));
        cnvTablero.setLocation(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width / 4, 0);
        cnvTablero.addMouseListener(new java.awt.event.MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                cnvTableroClick(e);
            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
        this.add(cnvTablero);
        pintarTablero();
    }

    /**
     * Método que extiende la pantalla a su máximo posible.
     */
    private void extenderPantalla() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    @Override
    protected void adaptarPantalla() {
        Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration());
        int taskBarHeight = screenInsets.bottom;
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

        this.setBounds(0, 0, ancho, alto - taskBarHeight);

        this.setPreferredSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
    }

    public static FrmSalir getFrmSalir() {
        if (frmSalir == null) {
            frmSalir = new FrmSalir();
        }
        return frmSalir;
    }

    private void pintarTablero() {
        cnvTablero.setCasillas(partida.getTablero().getCasillas());
        this.repaint();
        //cnvTablero.repaint();
        //  this.paintComponents(this.getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAvanzarNormal = new javax.swing.JButton();
        btnMeterFicha = new javax.swing.JButton();
        btnTirarCanias = new javax.swing.JButton();
        lblDado = new javax.swing.JLabel();
        btnRetirarse = new javax.swing.JButton();
        btnComenzarPartida = new javax.swing.JButton();
        lblFichasGanadoras = new javax.swing.JLabel();
        lblNumFrijoles = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        lblImgTurno = new javax.swing.JLabel();
        btnPagarApuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        btnAvanzarNormal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAvanzarNormal.setText("Avanzar Ficha del Turno");
        btnAvanzarNormal.setEnabled(false);
        btnAvanzarNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarNormalActionPerformed(evt);
            }
        });

        btnMeterFicha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMeterFicha.setText("Meter ficha");
        btnMeterFicha.setEnabled(false);
        btnMeterFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMeterFichaMouseClicked(evt);
            }
        });
        btnMeterFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeterFichaActionPerformed(evt);
            }
        });

        btnTirarCanias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTirarCanias.setText("Tirar cañas");
        btnTirarCanias.setEnabled(false);
        btnTirarCanias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTirarCaniasActionPerformed(evt);
            }
        });

        lblDado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDado.setText("Tiro: --");

        btnRetirarse.setText("Retirarse");
        btnRetirarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarseActionPerformed(evt);
            }
        });

        btnComenzarPartida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnComenzarPartida.setText("Comenzar partida");
        btnComenzarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComenzarPartidaMouseClicked(evt);
            }
        });
        btnComenzarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarPartidaActionPerformed(evt);
            }
        });

        lblFichasGanadoras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFichasGanadoras.setText("Has metido 0 fichas");

        lblNumFrijoles.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNumFrijoles.setText("Te quedan -- frijolitos");

        lblTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTurno.setText("Turno:");

        lblImgTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblImgTurno.setText("--");

        btnPagarApuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPagarApuesta.setText("Pagar apuesta");
        btnPagarApuesta.setEnabled(false);
        btnPagarApuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarApuestaMouseClicked(evt);
            }
        });
        btnPagarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarApuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetirarse, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAvanzarNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTirarCanias, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMeterFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFichasGanadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumFrijoles, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComenzarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagarApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImgTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTirarCanias, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImgTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMeterFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPagarApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnAvanzarNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lblFichasGanadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumFrijoles, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComenzarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnRetirarse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvanzarNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarNormalActionPerformed
        try {
            partida.setFichaMovimiento(jugador.getColaFichas().peek());

            if (partida.getFichaMovimiento() == null) {
                partida.setCantidadDado(-1);
            }

            cliente.enviar(partida);

        } catch (IOException ex) {
            Logger.getLogger(FrmTablero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAvanzarNormalActionPerformed

    private void btnMeterFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeterFichaActionPerformed
        try {
            jugador.setMeterFicha(true);
            partida.setJugadorTurno(jugador);
            cliente.enviar(partida);
        } catch (IOException ex) {
            Logger.getLogger(FrmTablero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMeterFichaActionPerformed

    private void btnTirarCaniasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTirarCaniasActionPerformed
        try {
            Random r = new Random();
            int tiro = r.nextInt(6);

            partida.setCantidadDado(tiro);
            partida.setFichaMovimiento(null);
            partida.setRepiteTurno(false);

            cliente.enviar(partida);

            btnTirarCanias.setEnabled(false);

        } catch (IOException ex) {
            Logger.getLogger(FrmTablero.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTirarCaniasActionPerformed

    private void btnRetirarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarseActionPerformed
        getFrmSalir().setVisible(true);
    }//GEN-LAST:event_btnRetirarseActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        cnvTablero.setLocation(this.getWidth() / 4, 0);
    }//GEN-LAST:event_formComponentResized

    private void btnComenzarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComenzarPartidaActionPerformed

    private void btnComenzarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComenzarPartidaMouseClicked
        try {
            partida.setEstado(EstadoPartida.INICIADA);
            partida.setJugadorTurno(jugador);
            cliente.enviar(partida);

        } catch (IOException ex) {
            Logger.getLogger(FrmTablero.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComenzarPartidaMouseClicked

    private void btnMeterFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeterFichaMouseClicked

    }//GEN-LAST:event_btnMeterFichaMouseClicked

    private void btnPagarApuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarApuestaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarApuestaMouseClicked

    private void btnPagarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarApuestaActionPerformed
        partida.setAvanzaPagando(true);
        btnAvanzarNormal.setEnabled(false);
        btnMeterFicha.setEnabled(false);
        btnPagarApuesta.setEnabled(false);
    }//GEN-LAST:event_btnPagarApuestaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzarNormal;
    private javax.swing.JButton btnComenzarPartida;
    private javax.swing.JButton btnMeterFicha;
    private javax.swing.JButton btnPagarApuesta;
    private javax.swing.JButton btnRetirarse;
    private javax.swing.JButton btnTirarCanias;
    private javax.swing.JLabel lblDado;
    private javax.swing.JLabel lblFichasGanadoras;
    private javax.swing.JLabel lblImgTurno;
    private javax.swing.JLabel lblNumFrijoles;
    private javax.swing.JLabel lblTurno;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Partida partidaLlegada) {
        super.update(partidaLlegada);
        actualizaJugador();
        pintarTablero();
        actualizarPantalla();
    }

    private void actualizarPantalla() {
        if (partida.getCantidadDado() != -1) {
            lblDado.setText("Tiro: " + partida.getCantidadDado());
        }

        if (partida.getCuantasMueve() == 0) {
            lblDado.setText("Tiro: " + partida.getCuantasMueve());
        }

        System.out.println(partida);
        if (partida.getEstado() == EstadoPartida.ESPERA && jugador.getNumJugador() == 1) {
            btnComenzarPartida.setVisible(true);
        } else {
            btnComenzarPartida.setVisible(false);
        }

        if (partida.getJugadorTurno().equals(jugador)&&partida.getEstado()!=EstadoPartida.TERMINADA) {
            if (partida.getCantidadDado() == -1 || partida.repiteTurno()) {
                btnTirarCanias.setEnabled(true);
            }

            if (partida.getCuantasMueve() != 0 && !partida.getJugadorTurno().getColaFichas().isEmpty()) {
                btnAvanzarNormal.setEnabled(true);
                if (partida.getJugadorTurno().getNumFrijoles() >= partida.getValorApuesta()) {
                    btnPagarApuesta.setEnabled(true);
                }
            }
            
            
            if (partida.getJugadorTurno().puedeMeter()) {
                btnMeterFicha.setEnabled(true);
            }else if (partida.getJugadorTurno().getColaFichas().isEmpty()&&!btnTirarCanias.isEnabled()) {
                try {
                    partida.setFichaMovimiento(null);
                    partida.setCantidadDado(-1);
                    partida.setCuantasMueve(0);
                    cliente.enviar(partida);

                } catch (IOException ex) {
                    Logger.getLogger(FrmTablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (btnTirarCanias.isEnabled()) {
                btnMeterFicha.setEnabled(false);
                btnPagarApuesta.setEnabled(false);
                btnAvanzarNormal.setEnabled(false);
            }
        } else {
            btnPagarApuesta.setEnabled(false);
            btnTirarCanias.setEnabled(false);
            btnMeterFicha.setEnabled(false);
            btnPagarApuesta.setEnabled(false);
            btnAvanzarNormal.setEnabled(false);
        }

        if (partida.getJugadorTurno() != null) {
            switch (partida.getJugadorTurno().getColor()) {
                case ROJO:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color rojo.png")));
                    break;
                case NARANJA:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color naranja.png")));
                    break;
                case AMARILLO:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color amarillo.png")));
                    break;
                case VERDE:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color verde.png")));
                    break;
                case CYAN:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color cyan.png")));
                    break;
                case AZUL:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color azul.png")));
                    break;
                case ROSA:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color rosa.png")));
                    break;
                case MORADO:
                    lblImgTurno.setIcon(new ImageIcon(getClass().getResource("/images/btn color morado.png")));
                    break;
            }
        }

    }

    private void cnvTableroClick(MouseEvent e) {
        if (partida.avanzaPagando() && partida.getJugadorTurno().equals(jugador)) {
            double x = e.getPoint().getX();
            double y = e.getPoint().getY();
            for (Casilla casilla : partida.getTablero().getCasillas()) {
                if (casilla.getFicha() != null && x >= casilla.getCoordenadaX() && x <= (casilla.getCoordenadaX() + 50) && y >= casilla.getCoordenadaY() && y <= (casilla.getCoordenadaY() + 50)) {
                    Ficha ficha = casilla.getFicha();
                    if (ficha.getJugador().equals(jugador)) {
                        try {
                            partida.setFichaMovimiento(ficha);
                            cliente.enviar(partida);
                        } catch (IOException ex) {
                            Logger.getLogger(FrmTablero.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;
                }
            }
        }
    }

    private void actualizaJugador() {
        for (Jugador jugadore : partida.getJugadores()) {
            if (jugadore.equals(jugador)) {
                jugador = jugadore;
                lblFichasGanadoras.setText("¡Llevas " + jugador.getFichasGanadoras().size() + " ficha(s)!");
                if (jugador.getNumFrijoles() > 0) {
                    lblNumFrijoles.setText("Te quedan " + jugador.getNumFrijoles() + " frijolito(s)");
                } else {
                    lblNumFrijoles.setText("Te has quedado sin frijolitos :(");
                }
            }
        }
    }
}
