/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Itzel
 */
public class FrmConfigurarPartida extends javax.swing.JFrame {

    /**
     * Creates new form FrmConfigurarSala
     */
    public FrmConfigurarPartida() {
        setUndecorated(true);
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumCasillas = new javax.swing.JLabel();
        lblNumFichas = new javax.swing.JLabel();
        lblApuesta = new javax.swing.JLabel();
        btnMenosCasillas = new javax.swing.JLabel();
        btnMasCasillas = new javax.swing.JLabel();
        lblCampoCasillas = new javax.swing.JLabel();
        btnMenosFichas = new javax.swing.JLabel();
        lblCampoFichas = new javax.swing.JLabel();
        btnMasFichas = new javax.swing.JLabel();
        btnMenosApuesta = new javax.swing.JLabel();
        lblCampoApuesta = new javax.swing.JLabel();
        btnMasApuesta = new javax.swing.JLabel();
        btnCrear = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumCasillas.setFont(new java.awt.Font("Eras Bold ITC", 0, 34)); // NOI18N
        lblNumCasillas.setForeground(new java.awt.Color(139, 89, 10));
        lblNumCasillas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasillas.setText("0");
        getContentPane().add(lblNumCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 100, 40));

        lblNumFichas.setFont(new java.awt.Font("Eras Bold ITC", 0, 34)); // NOI18N
        lblNumFichas.setForeground(new java.awt.Color(139, 89, 10));
        lblNumFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumFichas.setText("0");
        getContentPane().add(lblNumFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 100, 40));

        lblApuesta.setFont(new java.awt.Font("Eras Bold ITC", 0, 34)); // NOI18N
        lblApuesta.setForeground(new java.awt.Color(139, 89, 10));
        lblApuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblApuesta.setText("0");
        getContentPane().add(lblApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, 100, -1));

        btnMenosCasillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn menos.png"))); // NOI18N
        btnMenosCasillas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenosCasillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosCasillasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosCasillasMouseExited(evt);
            }
        });
        getContentPane().add(btnMenosCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 70, -1));

        btnMasCasillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn mas.png"))); // NOI18N
        btnMasCasillas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasCasillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasCasillasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasCasillasMouseExited(evt);
            }
        });
        getContentPane().add(btnMasCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 350, 70, -1));

        lblCampoCasillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo texto.png"))); // NOI18N
        getContentPane().add(lblCampoCasillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, -1, 80));

        btnMenosFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn menos.png"))); // NOI18N
        btnMenosFichas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenosFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosFichasMouseExited(evt);
            }
        });
        getContentPane().add(btnMenosFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 70, -1));

        lblCampoFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo texto.png"))); // NOI18N
        getContentPane().add(lblCampoFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, -1, 80));

        btnMasFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn mas.png"))); // NOI18N
        btnMasFichas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasFichasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasFichasMouseExited(evt);
            }
        });
        getContentPane().add(btnMasFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 520, 70, -1));

        btnMenosApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn menos.png"))); // NOI18N
        btnMenosApuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenosApuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosApuestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosApuestaMouseExited(evt);
            }
        });
        getContentPane().add(btnMenosApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 690, 70, -1));

        lblCampoApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo texto.png"))); // NOI18N
        getContentPane().add(lblCampoApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, -1, 80));

        btnMasApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn mas.png"))); // NOI18N
        btnMasApuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasApuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasApuestaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasApuestaMouseExited(evt);
            }
        });
        getContentPane().add(btnMasApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 690, 70, -1));

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn crear.png"))); // NOI18N
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 810, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn cancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 810, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frm config.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn cancelar 2.png"));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn cancelar.png"));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn crear 2.png"));
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn crear.png"));
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnMenosCasillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosCasillasMouseEntered
        btnMenosCasillas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn menos 2.png"));
    }//GEN-LAST:event_btnMenosCasillasMouseEntered

    private void btnMenosFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosFichasMouseEntered
        btnMenosFichas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn menos 2.png"));
    }//GEN-LAST:event_btnMenosFichasMouseEntered

    private void btnMenosApuestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosApuestaMouseEntered
        btnMenosApuesta.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn menos 2.png"));
    }//GEN-LAST:event_btnMenosApuestaMouseEntered

    private void btnMasCasillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasCasillasMouseEntered
        btnMasCasillas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn mas 2.png"));
    }//GEN-LAST:event_btnMasCasillasMouseEntered

    private void btnMasFichasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasFichasMouseEntered
        btnMasFichas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn mas 2.png"));
    }//GEN-LAST:event_btnMasFichasMouseEntered

    private void btnMasApuestaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasApuestaMouseEntered
        btnMasApuesta.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn mas 2.png"));
    }//GEN-LAST:event_btnMasApuestaMouseEntered

    private void btnMenosCasillasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosCasillasMouseExited
        btnMenosCasillas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn menos.png"));
    }//GEN-LAST:event_btnMenosCasillasMouseExited

    private void btnMenosFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosFichasMouseExited
        btnMenosFichas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn menos.png"));
    }//GEN-LAST:event_btnMenosFichasMouseExited

    private void btnMenosApuestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosApuestaMouseExited
        btnMenosApuesta.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn menos.png"));
    }//GEN-LAST:event_btnMenosApuestaMouseExited

    private void btnMasCasillasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasCasillasMouseExited
        btnMasCasillas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn mas.png"));
    }//GEN-LAST:event_btnMasCasillasMouseExited

    private void btnMasFichasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasFichasMouseExited
        btnMasFichas.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn mas.png"));
    }//GEN-LAST:event_btnMasFichasMouseExited

    private void btnMasApuestaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasApuestaMouseExited
        btnMasApuesta.setIcon(new ImageIcon("C:\\Users\\SPARTAN PC\\Documents\\NetBeansProjects\\Patolli\\images\\btn mas.png"));
    }//GEN-LAST:event_btnMasApuestaMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        FrmInicio inicio = new FrmInicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        FrmSeleccion seleccion = new FrmSeleccion();
        this.setVisible(false);
        seleccion.setVisible(true);
    }//GEN-LAST:event_btnCrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfigurarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCrear;
    private javax.swing.JLabel btnMasApuesta;
    private javax.swing.JLabel btnMasCasillas;
    private javax.swing.JLabel btnMasFichas;
    private javax.swing.JLabel btnMenosApuesta;
    private javax.swing.JLabel btnMenosCasillas;
    private javax.swing.JLabel btnMenosFichas;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblApuesta;
    private javax.swing.JLabel lblCampoApuesta;
    private javax.swing.JLabel lblCampoCasillas;
    private javax.swing.JLabel lblCampoFichas;
    private javax.swing.JLabel lblNumCasillas;
    private javax.swing.JLabel lblNumFichas;
    // End of variables declaration//GEN-END:variables
}
